version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
  
    depends_on:
      - auth-service
      - booking-service
      - business-service
      - resource-service

  auth-service:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  booking-service:
    build: ./services/booking
    env_file:
      - ./services/booking/.env
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  business-service:
    build: ./services/business
    env_file:
      - ./services/business/.env
    ports:
      - "3003:3003"
    depends_on:
      - postgres

  resource-service:
    build: ./services/resource
    env_file:
      - ./services/resource/.env
    ports:
      - "3004:3004"
    depends_on:
      - postgres