version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file:
      - ./api-gateway/.env
    volumes:
      - ./api-gateway:/app
      - gateway_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - auth-service
      - booking-service
      - business-service
      - resource-service

  auth-service:
    build: ./services/auth
    env_file:
      - ./services/auth/.env
    ports:
      - "3001:3001"
    volumes:
    - ./services/auth/src:/app/src
    - ./services/auth/logs:/app/logs
    - auth_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - postgres

  booking-service:
    build: ./services/booking
    env_file:
      - ./services/booking/.env
    ports:
      - "3002:3002"
    volumes:
      - ./services/booking:/app 
      - booking_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - postgres

  business-service:
    build: ./services/business
    env_file:
      - ./services/business/.env
    ports:
      - "3003:3003"
    volumes:
      - ./services/business/src:/app/src #only mount src
      - ./services/business/prisma:/app/prisma  # mount prisma schema
    command: npm run dev
    depends_on:
      - postgres

  resource-service:
    build: ./services/resource
    env_file:
      - ./services/resource/.env
    ports:
      - "3004:3004"
    volumes:
      - ./services/resource:/app
      - resource_node_modules:/app/node_modules
    command: npm run dev
    depends_on:
      - postgres

volumes:
  auth_node_modules:
  booking_node_modules:
  business_node_modules:
  resource_node_modules:
  gateway_node_modules: